apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: cicd-pipeline-new
  labels:
    app: cicd
description: cicd delivery pipeline
serialPipeline:
  stages:
  - targetId: dev
    # profiles:
    # - dev
  # - targetId: staging
  #   profiles:
  #   - staging
  # - targetId: prod
  #   profiles:
  #   - prod